### ISSUE TITLE
Prototype Todo

### ISSUE THREAD

**Issue by nathanjstratusadv** [stratusadv/django-glue#1]
- [x] Saving with custom calls and methods. Suggest using a model method called "django_glue_save" that is called when django_glus saves the object. Custom method need to be fed the request variable.
- [x] Glue connection for submit button based on unique name.
- [x] Glue connection for deleting object and having custom model method named "django_glue_delete that is called when you delete. Custom method need to be fed the request variable.
- [x] Create
- [x] Read
- [x] Update
- [x] Delete
- [x] Basic Javascript Framework that is Pythonic

**Comment by nathanjstratusadv** [comment]
Done the alpha!
